---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  api/clients:
    get:
      summary: index clients
      operationId: indexClients
      parameters:
      - name: limit
        in: query
        schema:
          type: integer
        required: false
      - name: offset
        in: query
        schema:
          type: integer
        required: false
      responses:
        '200':
          description: index clients
        '422':
          description: invalid request
    post:
      summary: create client
      operationId: createClients
      parameters: []
      responses:
        '200':
          description: index clients
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                wechat:
                  type: string
              required: []
  api/clients/{id}:
    get:
      summary: show client
      operationId: showClient
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: show client
    put:
      summary: update client
      operationId: updateClient
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: update client
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                wechat:
                  type: string
              required: []
  authentication/users/sign_in:
    post:
      summary: sign in
      operationId: signIn
      parameters: []
      responses:
        '200':
          description: signed in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
  authentication/users/sign_out:
    delete:
      summary: sign out
      operationId: signOut
      responses:
        '204':
          description: index clients
  authentication/users/:
    post:
      summary: sign up
      operationId: signUp
      parameters: []
      responses:
        '200':
          description: sign up
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
  "/api/current_user":
    get:
      summary: shows the current user
      operationId: currentUser
      responses:
        '200':
          description: user shown
servers:
- url: http://localhost:3000
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.jacky-client-book.ca
